name: Azure Linux VM Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: "true"
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
        #  terraform_version: 1.7.7

      - name: Terraform Init
        run: terraform init
        working-directory: linuxvmmodule

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: linuxvmmodule

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: linuxvmmodule
